# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("FedoraGooeyKarma")
        MainWindow.resize(1031, 766)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setAutoFillBackground(False)
        self.frame.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Karma = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Karma.setFont(font)
        self.Karma.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Karma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Karma.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Karma.setObjectName("Karma")
        self.gridLayout_2.addWidget(self.Karma, 11, 4, 1, 1)
        self.critpathBox = QtWidgets.QComboBox(self.frame)
        self.critpathBox.setObjectName("critpathBox")
        self.critpathBox.addItem("")
        self.critpathBox.addItem("")
        self.critpathBox.addItem("")
        self.gridLayout_2.addWidget(self.critpathBox, 25, 5, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 27, 6, 1, 2)
        self.Package_name_main = QtWidgets.QLabel(self.frame)
        self.Package_name_main.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.Package_name_main.setFont(font)
        self.Package_name_main.setObjectName("Package_name_main")
        self.gridLayout_2.addWidget(self.Package_name_main, 4, 3, 1, 4)
        self.critpathText = QtWidgets.QLabel(self.frame)
        self.critpathText.setObjectName("critpathText")
        self.gridLayout_2.addWidget(self.critpathText, 25, 4, 1, 1)
        self.karmaText = QtWidgets.QLabel(self.frame)
        self.karmaText.setObjectName("karmaText")
        self.gridLayout_2.addWidget(self.karmaText, 27, 4, 1, 1)
        self.commentEdit = QtWidgets.QTextEdit(self.frame)
        self.commentEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.commentEdit.setObjectName("commentEdit")
        self.gridLayout_2.addWidget(self.commentEdit, 17, 3, 1, 6)
        self.Release_notes = QtWidgets.QTextBrowser(self.frame)
        self.Release_notes.setObjectName("Release_notes")
        self.gridLayout_2.addWidget(self.Release_notes, 6, 3, 1, 6)
        self.Release = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Release.setFont(font)
        self.Release.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Release.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Release.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Release.setObjectName("Release")
        self.gridLayout_2.addWidget(self.Release, 8, 4, 1, 1)
        self.Release_static = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Release_static.setFont(font)
        self.Release_static.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Release_static.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Release_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Release_static.setObjectName("Release_static")
        self.gridLayout_2.addWidget(self.Release_static, 8, 3, 1, 1)
        self.UpdateType = QtWidgets.QLabel(self.frame)
        self.UpdateType.setObjectName("UpdateType")
        self.gridLayout_2.addWidget(self.UpdateType, 0, 3, 1, 1)
        self.Request = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Request.setFont(font)
        self.Request.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Request.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Request.setText("")
        self.Request.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Request.setObjectName("Request")
        self.gridLayout_2.addWidget(self.Request, 9, 6, 1, 1)
        self.Status_static = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Status_static.setFont(font)
        self.Status_static.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Status_static.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Status_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Status_static.setObjectName("Status_static")
        self.gridLayout_2.addWidget(self.Status_static, 8, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 16, 3, 1, 1)
        self.Submit_user = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Submit_user.setFont(font)
        self.Submit_user.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Submit_user.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Submit_user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Submit_user.setObjectName("Submit_user")
        self.gridLayout_2.addWidget(self.Submit_user, 11, 6, 1, 1)
        self.Date_static = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Date_static.setFont(font)
        self.Date_static.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Date_static.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Date_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Date_static.setObjectName("Date_static")
        self.gridLayout_2.addWidget(self.Date_static, 9, 3, 1, 1)
        self.Karma_static = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Karma_static.setFont(font)
        self.Karma_static.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Karma_static.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Karma_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Karma_static.setObjectName("Karma_static")
        self.gridLayout_2.addWidget(self.Karma_static, 11, 3, 1, 1)
        self.karmaBox = QtWidgets.QComboBox(self.frame)
        self.karmaBox.setObjectName("karmaBox")
        self.karmaBox.addItem("")
        self.karmaBox.addItem("")
        self.karmaBox.addItem("")
        self.gridLayout_2.addWidget(self.karmaBox, 27, 5, 1, 1)
        self.Date_submitted = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Date_submitted.setFont(font)
        self.Date_submitted.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Date_submitted.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Date_submitted.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Date_submitted.setObjectName("Date_submitted")
        self.gridLayout_2.addWidget(self.Date_submitted, 9, 4, 1, 1)
        self.Status = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Status.setFont(font)
        self.Status.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Status.setObjectName("Status")
        self.gridLayout_2.addWidget(self.Status, 8, 6, 1, 1)
        self.treeWidget_comment = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget_comment.setObjectName("treeWidget_comment")
        self.gridLayout_2.addWidget(self.treeWidget_comment, 12, 3, 1, 6)
        self.Package_breif = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Package_breif.setFont(font)
        self.Package_breif.setObjectName("Package_breif")
        self.gridLayout_2.addWidget(self.Package_breif, 5, 3, 1, 1)
        self.Request_static = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Request_static.setFont(font)
        self.Request_static.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Request_static.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Request_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Request_static.setObjectName("Request_static")
        self.gridLayout_2.addWidget(self.Request_static, 9, 5, 1, 1)
        self.Submitter_static = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Submitter_static.setFont(font)
        self.Submitter_static.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Submitter_static.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Submitter_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Submitter_static.setObjectName("Submitter_static")
        self.gridLayout_2.addWidget(self.Submitter_static, 11, 5, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 600))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.frame_2)
        self.searchButton.setMaximumSize(QtCore.QSize(50, 50))
        self.searchButton.setObjectName("searchButton")
        self.gridLayout_4.addWidget(self.searchButton, 0, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_4.addWidget(self.listWidget, 2, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PageNum = QtWidgets.QLabel(self.frame_3)
        self.PageNum.setObjectName("PageNum")
        self.gridLayout_3.addWidget(self.PageNum, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.nextButton = QtWidgets.QPushButton(self.frame_3)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout_3.addWidget(self.nextButton, 0, 2, 1, 1)
        self.previousButton = QtWidgets.QPushButton(self.frame_3)
        self.previousButton.setObjectName("previousButton")
        self.gridLayout_3.addWidget(self.previousButton, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 3, 0, 1, 2)
        self.fetchUpdatesButton = QtWidgets.QPushButton(self.frame_2)
        self.fetchUpdatesButton.setObjectName("fetchUpdatesButton")
        self.gridLayout_4.addWidget(self.fetchUpdatesButton, 4, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 28, 1)
        self.Karma_static.raise_()
        self.frame_2.raise_()
        self.Package_breif.raise_()
        self.commentEdit.raise_()
        self.Package_name_main.raise_()
        self.Release_static.raise_()
        self.Date_static.raise_()
        self.pushButton.raise_()
        self.Release.raise_()
        self.Date_submitted.raise_()
        self.Karma.raise_()
        self.Submitter_static.raise_()
        self.Request_static.raise_()
        self.Submit_user.raise_()
        self.Status_static.raise_()
        self.Status.raise_()
        self.Request.raise_()
        self.UpdateType.raise_()
        self.karmaBox.raise_()
        self.karmaText.raise_()
        self.label_2.raise_()
        self.Release_notes.raise_()
        self.treeWidget_comment.raise_()
        self.critpathText.raise_()
        self.critpathBox.raise_()
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 5)
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setObjectName("loginButton")
        self.gridLayout.addWidget(self.loginButton, 1, 4, 1, 1)
        self.usernamLable = QtWidgets.QLabel(self.centralwidget)
        self.usernamLable.setObjectName("usernamLable")
        self.gridLayout.addWidget(self.usernamLable, 1, 3, 1, 1, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.critpathBox.setCurrentIndex(1)
        self.karmaBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Karma.setText(_translate("MainWindow", "__"))
        self.critpathBox.setCurrentText(_translate("MainWindow", "0"))
        self.critpathBox.setItemText(0, _translate("MainWindow", "1"))
        self.critpathBox.setItemText(1, _translate("MainWindow", "0"))
        self.critpathBox.setItemText(2, _translate("MainWindow", "-1"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.Package_name_main.setText(_translate("MainWindow", "Package Name"))
        self.critpathText.setText(_translate("MainWindow", "critpath"))
        self.karmaText.setText(_translate("MainWindow", "Karma"))
        self.Release.setText(_translate("MainWindow", "__"))
        self.Release_static.setText(_translate("MainWindow", "Release"))
        self.UpdateType.setText(_translate("MainWindow", "__"))
        self.Status_static.setText(_translate("MainWindow", "Status"))
        self.label_2.setText(_translate("MainWindow", "Comment"))
        self.Submit_user.setText(_translate("MainWindow", "__"))
        self.Date_static.setText(_translate("MainWindow", "date submitted"))
        self.Karma_static.setText(_translate("MainWindow", "Karma"))
        self.karmaBox.setCurrentText(_translate("MainWindow", "0"))
        self.karmaBox.setItemText(0, _translate("MainWindow", "1"))
        self.karmaBox.setItemText(1, _translate("MainWindow", "0"))
        self.karmaBox.setItemText(2, _translate("MainWindow", "-1"))
        self.Date_submitted.setText(_translate("MainWindow", "__"))
        self.Status.setText(_translate("MainWindow", "__"))
        self.treeWidget_comment.headerItem().setText(0, _translate("MainWindow", "#"))
        self.treeWidget_comment.headerItem().setText(1, _translate("MainWindow", "karma"))
        self.treeWidget_comment.headerItem().setText(2, _translate("MainWindow", "critpath"))
        self.treeWidget_comment.headerItem().setText(3, _translate("MainWindow", "user"))
        self.treeWidget_comment.headerItem().setText(4, _translate("MainWindow", "comment"))
        self.Package_breif.setText(_translate("MainWindow", "breif"))
        self.Request_static.setText(_translate("MainWindow", "Request"))
        self.Submitter_static.setText(_translate("MainWindow", "Submitter"))
        self.searchButton.setText(_translate("MainWindow", "🔍"))
        self.PageNum.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "Page number:"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.previousButton.setText(_translate("MainWindow", "Previous"))
        self.fetchUpdatesButton.setText(_translate("MainWindow", "Fetch Updates"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.usernamLable.setText(_translate("MainWindow", "Username"))
